DROP TABLE IF EXISTS user_role cascade ;
DROP TABLE IF EXISTS role cascade;
DROP TABLE IF EXISTS user cascade;

create table User (
                      id bigint generated by default as identity,
                      email varchar(255),
                      name varchar(255),
                      primary key (id)
);

create table Role (
                      role_id bigint generated by default as identity,
                      name varchar(255),
                      primary key (role_id)
);

create table User_Role (
                           User_id bigint not null,
                           roles_role_id bigint not null,
                           primary key (User_id, roles_role_id)
);

INSERT INTO User (id, name, email) VALUES
(1,'Иван Иванов', 'ivan@mail.ru'),
(2,'Иван Петров', 'ivanpet@mail.ru'),
(3,'Дмитрий О', 'dima@mail.ru'),
(4,'Олег А', 'oleg@mail.ru'),
(5,'Валерий У', 'valer@mail.ru');

INSERT INTO Role (role_id, name) VALUES
(1 ,'admin'),
(2 ,'owner');

INSERT INTO User_Role (User_id, roles_role_id) VALUES
(1 , 1),
(2 , 2),
(3 , 1),
(4 , 2),
(5 , 1);
